spring.application.name=akasa-airline-backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/akasa-airline-db
spring.datasource.username=root
spring.datasource.password=Chetan@0713

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true